[package]
name = "aziot-key-openssl-engine-shared"
version = "0.1.0"
license = "MIT"
authors = ["Arnav Singh <arsing@microsoft.com>"]
edition = "2021"
build = "build/main.rs"


[lib]
crate-type = ["cdylib"]


[dependencies]
openssl-errors = "0.2"
openssl-sys = "0.9"
url = "2"

aziot-key-client = { path = "../aziot-key-client" }
aziot-key-common-http = { path = "../aziot-key-common-http" }
aziot-key-openssl-engine = { path = "../aziot-key-openssl-engine" }
http-common = { path = "../../http-common" }
openssl-sys2 = { path = "../../openssl-sys2" }


[build-dependencies]
openssl-build = { path = "../../openssl-build" }
