homedir_path = "/var/lib/aziot/certd"
[cert_issuance.est]
username = "estuser"
password = "estpwd"
identity_cert = "est-id"
identity_pk = "est-id"
trusted_certs = ["est-server-ca"]

[cert_issuance.est.urls]
default = "https://example.org/.well-known/est"
device-id = "https://example.org/.well-known/est/device-id"

[cert_issuance.device-id]
method = "est"
common_name = "my-device"

[preloaded_certs]
est-id = "file:///var/secrets/est-id.pem"
est-server-ca = "file:///var/secrets/est-id-ca.pem"
