[provisioning]
source = "manual"
connection_string = "HostName=example.azure-devices.net;DeviceId=my-device;SharedAccessKey=YXppb3QtaWRlbnRpdHktc2VydmljZXxhemlvdC1pZGU="

[aziot_max_requests]
keyd = 20
certd = 30
tpmd = 40
identityd = 50
