homedir_path = "/var/lib/aziot/certd"

[cert_issuance.est]
trusted_certs = ["est-server-ca-1"]
username = "estuser"
password = "estpwd"
identity_cert = "est-id"
identity_pk = "est-id"

[cert_issuance.est.urls]
default = "https://example.org/.well-known/est"

[cert_issuance.device-id]
method = "est"
common_name = "my-device"

[preloaded_certs]
est-id = "file:///var/secrets/est-id.pem"
est-server-ca-1 = "file:///var/secrets/est-id-ca.pem"

[[principal]]
uid = 5556
certs = ["device-id"]
