[package]
name = "config-common"
version = "0.1.0"
authors = ["Rajeev Massand <massand@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backtrace = "0.3"
serde = "1"
toml = "0.5"
