[package]
name = "config-common"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
edition = "2018"


[dependencies]
async-trait = "0.1"
backtrace = "0.3"
futures-util = "0.3"
log = "0.4"
notify = "4"
serde = "1"
tokio = { version = "1", features = ["rt", "sync"] }
toml = "0.5"
