[package]
name = "aziot-key-client-async"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
edition = "2018"

[dependencies]
http = "0.2"
hyper = "0.14"
percent-encoding = "2"
serde = "1"
serde_json = "1"

http-common = { path = "../../http-common", features = ["tokio02"] }
aziot-key-common = { path = "../aziot-key-common" }
aziot-key-common-http = { path = "../aziot-key-common-http" }
