[package]
name = "tpm2-tss-sys"
version = "0.1.0"
edition = "2021"
# Not actually linking anything, just getting cargo to propagate
# installation prefix through DEP_TPM2_TSS_ROOT.
links = "tpm2-tss"

[lib]
path = "lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["static"]
dynamic = []
static = []
