[package]
name = "types-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = { version = "0.59", features = ["runtime"], default-features = false }
pkg-config = "0.3"

tpm2-tss-sys = { path = "../tpm2-tss-sys", optional = true }

[features]
vendor = ["dep:tpm2-tss-sys"]
