[package]
name = "aziot-key-client"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
edition = "2018"

[dependencies]
http = "0.2"
httparse = "1"
percent-encoding = "2"
serde = "1"
serde_json = "1"

aziot-key-common = { path = "../aziot-key-common" }
aziot-key-common-http = { path = "../aziot-key-common-http" }
http-common = { path = "../../http-common" }
