[package]
name = "mu-sys"
version = "0.1.0"
edition = "2021"
links = "tss2-mu"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types-sys = { path = "../types-sys" }

tpm2-tss-sys = { path = "../tpm2-tss-sys", optional = true }

[build-dependencies]
bindgen = { version = "0.59", features = ["runtime"], default-features = false }
pkg-config = "0.3"

[features]
vendor = ["dep:tpm2-tss-sys", "types-sys/vendor"]
