[package]
name = "tcti-sys"
version = "0.1.0"
edition = "2021"
links = "tss2-tctildr"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = { version = "0.64", features = ["runtime"], default-features = false }
# NOTE: Version >= 0.3.20 necessary for cross-builds.
# Ref: https://github.com/rust-lang/pkg-config-rs/blob/master/CHANGELOG.md#0320---2021-09-25
pkg-config = "0.3.20"
