[package]
name = "aziot-tpm-common-http"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }

http-common = { path = "../../http-common" }
