[provisioning]
source = "manual"
iothub_hostname = "example.azure-devices.net"
device_id = "my-device"

[provisioning.authentication]
method = "x509"
identity_cert = "file:///var/secrets/device-id.pem"
identity_pk = "pkcs11:slot-id=0;object=device-id?pin-value=1234"

[aziot_keys]
pkcs11_lib_path = "/usr/lib/libmypkcs11.so"
pkcs11_base_slot = "pkcs11:slot-id=0?pin-value=1234"
