[provisioning]
source = "manual"
iothub_hostname = "example.azure-devices.net"
device_id = "my-device"

[provisioning.authentication]
method = "x509"
identity_cert = "file:///var/secrets/device-id.pem"
identity_pk = "file:///var/secrets/device-id.key.pem"
