[package]
name = "aziot-keyd-config"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
edition = "2021"


[dependencies]
libc = "0.2"
serde = { version = "1", features = ["derive"] }

http-common = { path = "../../http-common" }

[dev-dependencies]
toml = "0.7"
