#!/bin/bash

mkdir -p $SNAP_DATA/shared/{secrets,sockets}/aziot
mkdir -p $SNAP_DATA/shared/config/aziot/{keyd,certd,identityd,tpmd}/config.d
mkdir -p $SNAP_DATA/var/lib/{aziot/{keyd,certd,identityd,tpmd},tpm}
mkdir -p $SNAP_COMMON/libaziot_keys_homedir
